version: '3'
services:
  php:
    image: "jolka/jolka_php"
    ports:
     - "8080:80"
    volumes:
     - ../fasolka:/app/fasolka
    depends_on:
     - mysql
    links:
     - mysql:db
  pma:
    image: "jolka/jolka_pma"
    ports:
     - "8081:80"
    depends_on:
     - mysql
    links:
     - mysql:db
  mysql:
    image: "mysql"
    volumes:
     - dbPanda:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=jolka

  volumes:
    dbPanda: