version: '3'
services:
  php:
    container_name: php
    image: "jolka/jolka_php"
    ports:
     - "8080:80"
    volumes:
     - ../fasolka:/app/fasolka
    depends_on:
     - mysql
    links:
     - mysql:db

  pma:
    container_name: pma
    image: "jolka/jolka_pma"
    ports:
     - "8081:80"
    depends_on:
     - mysql
    links:
     - mysql:db